insert into appbid_category(`id`,`apple_id`,`name`) values(1,6018,'Books');
insert into appbid_category(`id`,`apple_id`,`name`) values(2,6000,'Business');
insert into appbid_category(`id`,`apple_id`,`name`) values(3,6022,'Catalogs');
insert into appbid_category(`id`,`apple_id`,`name`) values(4,6017,'Education');
insert into appbid_category(`id`,`apple_id`,`name`) values(5,6016,'Entertainment');
insert into appbid_category(`id`,`apple_id`,`name`) values(6,6015,'Finance');
insert into appbid_category(`id`,`apple_id`,`name`) values(7,6023,'Food & Drink');
insert into appbid_category(`id`,`apple_id`,`name`) values(8,6014,'Games');
insert into appbid_category(`id`,`apple_id`,`name`) values(9,6013,'Health & Fitness');
insert into appbid_category(`id`,`apple_id`,`name`) values(10,6012,'Lifestyle');
insert into appbid_category(`id`,`apple_id`,`name`) values(11,6020,'Medical');
insert into appbid_category(`id`,`apple_id`,`name`) values(12,6011,'Music');
insert into appbid_category(`id`,`apple_id`,`name`) values(13,6010,'Navigation');
insert into appbid_category(`id`,`apple_id`,`name`) values(14,6009,'News');
insert into appbid_category(`id`,`apple_id`,`name`) values(15,6021,'Newsstand');
insert into appbid_category(`id`,`apple_id`,`name`) values(16,6008,'Photo & Video');
insert into appbid_category(`id`,`apple_id`,`name`) values(17,6007,'Productivity');
insert into appbid_category(`id`,`apple_id`,`name`) values(18,6006,'Reference');
insert into appbid_category(`id`,`apple_id`,`name`) values(19,6005,'Social Networking');
insert into appbid_category(`id`,`apple_id`,`name`) values(20,6004,'Sports');
insert into appbid_category(`id`,`apple_id`,`name`) values(21,6003,'Travel');
insert into appbid_category(`id`,`apple_id`,`name`) values(22,6002,'Utilities');
insert into appbid_category(`id`,`apple_id`,`name`) values(23,6001,'Weather');