insert into appbid_subcategory(`category_id`,`apple_id`,`name`) values('8',7001,'Action');
insert into appbid_subcategory(`category_id`,`apple_id`,`name`) values('8',7002,'Adventure');
insert into appbid_subcategory(`category_id`,`apple_id`,`name`) values('8',7003,'Arcade');
insert into appbid_subcategory(`category_id`,`apple_id`,`name`) values('8',7004,'Board');
insert into appbid_subcategory(`category_id`,`apple_id`,`name`) values('8',7005,'Card');
insert into appbid_subcategory(`category_id`,`apple_id`,`name`) values('8',7006,'Casino');
insert into appbid_subcategory(`category_id`,`apple_id`,`name`) values('8',7007,'Dice');
insert into appbid_subcategory(`category_id`,`apple_id`,`name`) values('8',7008,'Educational');
insert into appbid_subcategory(`category_id`,`apple_id`,`name`) values('8',7009,'Family');
insert into appbid_subcategory(`category_id`,`apple_id`,`name`) values('8',7010,'Kids');
insert into appbid_subcategory(`category_id`,`apple_id`,`name`) values('8',7011,'Music');
insert into appbid_subcategory(`category_id`,`apple_id`,`name`) values('8',7012,'Puzzle');
insert into appbid_subcategory(`category_id`,`apple_id`,`name`) values('8',7013,'Racing');
insert into appbid_subcategory(`category_id`,`apple_id`,`name`) values('8',7014,'Role Playing');
insert into appbid_subcategory(`category_id`,`apple_id`,`name`) values('8',7015,'Simulation');
insert into appbid_subcategory(`category_id`,`apple_id`,`name`) values('8',7016,'Sports');
insert into appbid_subcategory(`category_id`,`apple_id`,`name`) values('8',7017,'Strategy');
insert into appbid_subcategory(`category_id`,`apple_id`,`name`) values('8',7018,'Trivia');
insert into appbid_subcategory(`category_id`,`apple_id`,`name`) values('8',7019,'Word');
insert into appbid_subcategory(`category_id`,`apple_id`,`name`) values('15',13007,'Arts & Photography');
insert into appbid_subcategory(`category_id`,`apple_id`,`name`) values('15',13006,'Automotive');
insert into appbid_subcategory(`category_id`,`apple_id`,`name`) values('15',13008,'Brides & Weddings');
insert into appbid_subcategory(`category_id`,`apple_id`,`name`) values('15',13009,'Business & Investing');
insert into appbid_subcategory(`category_id`,`apple_id`,`name`) values('15',13010,'Children\'s Magazines');
insert into appbid_subcategory(`category_id`,`apple_id`,`name`) values('15',13011,'Computers & Internet');
insert into appbid_subcategory(`category_id`,`apple_id`,`name`) values('15',13012,'Cooking, Food & Drink');
insert into appbid_subcategory(`category_id`,`apple_id`,`name`) values('15',13013,'Crafts & Hobbies');
insert into appbid_subcategory(`category_id`,`apple_id`,`name`) values('15',13014,'Electronics & Audio');
insert into appbid_subcategory(`category_id`,`apple_id`,`name`) values('15',13015,'Entertainment');
insert into appbid_subcategory(`category_id`,`apple_id`,`name`) values('15',13002,'Fashion & Style');
insert into appbid_subcategory(`category_id`,`apple_id`,`name`) values('15',13017,'Health, Mind & Body');
insert into appbid_subcategory(`category_id`,`apple_id`,`name`) values('15',13018,'History');
insert into appbid_subcategory(`category_id`,`apple_id`,`name`) values('15',13003,'Home & Garden');
insert into appbid_subcategory(`category_id`,`apple_id`,`name`) values('15',13019,'Literary Magazines & Journals');
insert into appbid_subcategory(`category_id`,`apple_id`,`name`) values('15',13020,'Men\'s Interest');
insert into appbid_subcategory(`category_id`,`apple_id`,`name`) values('15',13021,'Movies & Music');
insert into appbid_subcategory(`category_id`,`apple_id`,`name`) values('15',13001,'News & Politics');
insert into appbid_subcategory(`category_id`,`apple_id`,`name`) values('15',13004,'Outdoors & Nature');
insert into appbid_subcategory(`category_id`,`apple_id`,`name`) values('15',13023,'Parenting & Family');
insert into appbid_subcategory(`category_id`,`apple_id`,`name`) values('15',13024,'Pets');
insert into appbid_subcategory(`category_id`,`apple_id`,`name`) values('15',13025,'Professional & Trade');
insert into appbid_subcategory(`category_id`,`apple_id`,`name`) values('15',13026,'Regional News');
insert into appbid_subcategory(`category_id`,`apple_id`,`name`) values('15',13027,'Science');
insert into appbid_subcategory(`category_id`,`apple_id`,`name`) values('15',13005,'Sports & Leisure');
insert into appbid_subcategory(`category_id`,`apple_id`,`name`) values('15',13028,'Teens');
insert into appbid_subcategory(`category_id`,`apple_id`,`name`) values('15',13029,'Travel & Regional');
insert into appbid_subcategory(`category_id`,`apple_id`,`name`) values('15',13030,'Women\'s Interest');