insert into system_systemparam(`key`,`value`,`description`) values('token_len','10','Verify token length.');
insert into system_systemparam(`key`,`value`,`description`) values('max_num_attachment','50','The max number of uploading the attachment.');
insert into system_systemparam(`key`,`value`,`description`) values('attachment_size','50000000','The attachment size can not be more than 50M.');
insert into system_systemparam(`key`,`value`,`description`) values('discount_rate','0','The discount rate of price,such as 1(no discount) 0.9, 0.8, 0(free).');
insert into system_systemparam(`key`,`value`,`description`) values('minimum_bid','10','The default minimum_bid is 10 CNY or USD.');
insert into system_systemparam(`key`,`value`,`description`) values('service_expiry_date','31','The default service expiry date for app is 31 days.');
insert into system_systemparam(`key`,`value`,`description`) values('token_length','30','The length of token in system.');
insert into system_systemparam(`key`,`value`,`description`) values('page_range','10','The maximum number of items to include on a page.');
insert into system_systemparam(`key`,`value`,`description`) values('currency','2','The default currency is 2 - USD.');
insert into system_systemparam(`key`,`value`,`description`) values('monetize','4','The default monetize is 4 - Free.');
insert into system_systemparam(`key`,`value`,`description`) values('sell_expiry_date','7','The expiry date of seller sell app or not is 7 days.');
insert into system_systemparam(`key`,`value`,`description`) values('paid_expiry_date','7','The expiry date of buyer paid is 7 days.');
insert into system_systemparam(`key`,`value`,`description`) values('txn_expiry_date','15','The expiry date of app transaction is 15 days.');
insert into system_systemparam(`key`,`value`,`description`) values('cp_init_number','100','The default credit point is 100.');
insert into system_systemparam(`key`,`value`,`description`) values('cp_closed_trade','50','After trade closed successfully, increase seller and buyer credit point.');
insert into system_systemparam(`key`,`value`,`description`) values('cp_no_closed_trade','50','If buyer unpaid in paid_expiry_date, decrease seller buyer credit point.');
insert into system_systemparam(`key`,`value`,`description`) values('cp_buyer_unpaid','50','If buyer unpaid in paid_expiry_date, decrease buyer credit point.');
insert into system_systemparam(`key`,`value`,`description`) values('min_cp_for_bid','50','Buyer credit point need have more than this value.');
insert into system_systemparam(`key`,`value`,`description`) values('txn_fee_pct','0.01','AppsWalk charge the percent of transaction fee in app trading.');
insert into system_systemparam(`key`,`value`,`description`) values('support_user','appswalk','The support account for such as user complain.');
