insert into system_systemparam(`key`,`value`,`description`) values('token_len','10','Verify token length.');
insert into system_systemparam(`key`,`value`,`description`) values('max_num_attachment','50','The max number of uploading the attachment.');
insert into system_systemparam(`key`,`value`,`description`) values('attachment_size','50000000','The attachment size can not be more than 50M.');
insert into system_systemparam(`key`,`value`,`description`) values('discount_rate','0','The discount rate of price,such as 1(no discount) 0.9, 0.8, 0(free).');
insert into system_systemparam(`key`,`value`,`description`) values('minimum_bid','10','The default minimum_bid is 10 CNY or USD.');
insert into system_systemparam(`key`,`value`,`description`) values('service_expiry_date','1','The default service expiry date for app is 1 month.');
insert into system_systemparam(`key`,`value`,`description`) values('active_link_confirm_token_length','30','The length of confirm token in user account active link.');
insert into system_systemparam(`key`,`value`,`description`) values('page_range','10','The maximum number of items to include on a page.');
insert into system_systemparam(`key`,`value`,`description`) values('currency','2','The default currency is 2 - USD.');
insert into system_systemparam(`key`,`value`,`description`) values('monetize','4','The default monetize is 4 - Free.');