from django.conf.urls import patterns, url
from seller import views

urlpatterns = patterns('',
    url(r'^appStore_link/(?P<pk>\d*)$', views.register_app,
        {'flag': 1.1,
         'backPage': 'seller/register_content.html',
         'nextPage': 'seller:appStore_info',
         'saveMethod': views.saveAppStoreLink,
         }, name='appStore_link'),
    url(r'^appStore_info/(?P<pk>\d*)$', views.register_app,
        {'flag': 1.2,
         'backPage': 'seller/register_content.html',
         'nextPage': 'seller:marketing',
         'saveMethod': views.saveAppStoreInfo,
         }, name='appStore_info'),
    url(r'^marketing/(?P<pk>\d*)$', views.register_app,
        {'flag': 2,
         'backPage': 'seller/register_content.html',
         'nextPage': 'seller:additional_info',
         'saveMethod': views.saveMarketing,
         }, name='marketing'),
    url(r'^additional_info/(?P<pk>\d*)$', views.register_app,
        {'flag': 3,
         'backPage': 'seller/register_content.html',
         'nextPage': 'seller:sale',
         'saveMethod': views.saveAdditionalInfo,
         }, name='additional_info'),
    url(r'^sale/(?P<pk>\d*)$', views.register_app,
        {'flag': 4,
         'backPage': 'seller/register_content.html',
         'nextPage': 'seller:delivery',
         'saveMethod': views.saveSale,
         }, name='sale'),
    url(r'^delivery/(?P<pk>\d*)$', views.register_app,
        {'flag': 5,
         'backPage': 'seller/register_content.html',
         'nextPage': 'seller:payment',
         'saveMethod': views.saveDelivery,
         }, name='delivery'),
    url(r'^payment/(?P<pk>\d*)$', views.register_app,
        {'flag': 6,
         'backPage': 'seller/register_content.html',
         'nextPage': 'seller:verification',
         'saveMethod': views.savePayment,
         }, name='payment'),
    url(r'^verification/(?P<pk>\d*)$', views.register_app,
        {'flag': 7,
         'backPage': 'seller/register_content.html',
         'nextPage': 'seller:verification',#TODO: need redirect to other page.
         'saveMethod': views.saveVerification,
         }, name='verification'),
)
